name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"

      - name: Bump Version
        run: node bump-version.js

      - name: Commit Version Bump
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git add manifest.json
          git commit -m "Bump version [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip Extension Files
        run: zip -r edge-extension.zip . -x ".*" "*.zip" "LICENSE" "README.md" "bump-version.js" "node_modules/*"

      - name: Publish Extension to Edge Store
        run: |
          response=$(curl \
          -H "Authorization: ApiKey ${{ secrets.EDGE_ACCESS_TOKEN }}" \
          -H "X-ClientID: ${{ secrets.EDGE_CLIENT_ID }}" \
          -H "Content-Type: application/zip" \
          -X POST \
          -T edge-extension.zip \
          -v \
          https://api.addons.microsoftedge.microsoft.com/v1/products/${{ secrets.EDGE_PRODUCT_ID }}/submissions/draft/packages)

          echo "Response: $response"
          if [[ "$response" != *"200"* ]]; then
            echo "Error: Publishing failed."
            exit 1
          fi
