name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # No npm tests are run since the project does not use Node tooling.
      - name: Bump version
        run: node bump-version.js

      - name: Commit version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git add manifest.json
          git commit -m "Bump version" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: edge-extension
          path: |
            ./**
            !./**/.*
            !./.git/**
            !./.github/**
            !./.gitignore
            !./LICENSE
            !./README.md
            !./bump-version.js
            !./package.json
            !./package-lock.json
            !./**/*screenshot*
            !./**/*.zip
