name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # No npm tests are run since the project does not use Node tooling.
      - name: Bump version
        run: node bump-version.js

      - name: Commit version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git add manifest.json
          git commit -m "Bump version" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Package extension
        run: zip -r edge-extension.zip . -x ".*" "*.zip" "LICENSE" "README.md" "bump-version.js" "*screenshot*"

      - name: Publish to Edge Add-ons
        env:
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_API_KEY: ${{ secrets.EDGE_API_KEY }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
        run: |
          set -e
          curl -fsS -o /dev/null -X POST "https://api.addons.microsoftedge.microsoft.com/v1/products/$EDGE_PRODUCT_ID/submissions/draft" \
            -H "Authorization: ApiKey $EDGE_API_KEY" \
            -H "X-ClientID: $EDGE_CLIENT_ID" \
            -H "Content-Type: application/json" \
            --data ""

          curl -fsS -o /dev/null -X POST "https://api.addons.microsoftedge.microsoft.com/v1/products/$EDGE_PRODUCT_ID/submissions/draft/package" \
            -H "Authorization: ApiKey $EDGE_API_KEY" \
            -H "X-ClientID: $EDGE_CLIENT_ID" \
            -H "Content-Type: application/zip" \
            --data-binary @edge-extension.zip

          echo "Waiting for package processing..."
          for i in {1..30}; do
            status=$(curl -fsS -X GET "https://api.addons.microsoftedge.microsoft.com/v1/products/$EDGE_PRODUCT_ID/submissions/draft" \
              -H "Authorization: ApiKey $EDGE_API_KEY" \
              -H "X-ClientID: $EDGE_CLIENT_ID" \
              -H "Content-Type: application/json" | jq -r '.status')
            [ "$status" = "Succeeded" ] && break
            echo "Current status: $status. Retrying in 10s..."
            sleep 10
          done
          [ "$status" = "Succeeded" ] || { echo "Error: package processing status $status"; exit 1; }

          publish_headers=$(curl -fsS -D - -o /dev/null -X POST "https://api.addons.microsoftedge.microsoft.com/v1/products/$EDGE_PRODUCT_ID/submissions/draft/publish" \
            -H "Authorization: ApiKey $EDGE_API_KEY" \
            -H "X-ClientID: $EDGE_CLIENT_ID" \
            -H "Content-Type: application/json")

          operation_url=$(echo "$publish_headers" | tr -d '\r' | grep -i '^operation-location:' | awk '{print $2}')

          echo "Waiting for publish to complete..."
          for i in {1..30}; do
            publish_status=$(curl -fsS -X GET "$operation_url" \
              -H "Authorization: ApiKey $EDGE_API_KEY" \
              -H "X-ClientID: $EDGE_CLIENT_ID" \
              -H "Content-Type: application/json" | jq -r '.status')
            [ "$publish_status" = "Succeeded" ] && break
            echo "Current publish status: $publish_status. Retrying in 10s..."
            sleep 10
          done
          [ "$publish_status" = "Succeeded" ] || { echo "Error: publish status $publish_status"; exit 1; }

